### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by binayakpokhrel** [rozumden/fmo-cpp-demo#1]
Hello there,
I am a Ubuntu 18.04 user and was trying out your application but couldn't run the application due to following error

command:::  ```fmo-desktop --camera 0 --utiademo```

Result:-
```fmo-desktop: error while loading shared libraries: libopencv_highgui.so.3.1: cannot open shared```
```object file: No such file or directory
```

**Comment by rozumden** [comment]
Hello, it seems to be related to OpenCV library. Are you sure you have installed it correctly? What version of OpenCV do you have? It's looking for version 3.1.

**Comment by binayakpokhrel** [comment]
@rozumden  Thanks for the quick reply...Works like a charm, you guys have done a great job.
