### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by HANAND1979** [rozumden/fmo-cpp-demo#2]
Hi,

Thank you for publishing such a great work. It is very informative.

I am trying to build your code on MacOS. When i run the 'make' command, am getting the following error.

Can you please look into it? I am not able to figure out how to fix this issue. Thank you in advance.

Note: In the below error messages i had to remove few of the 'tilda' symbols as the github markup was treating it as a strikethrough. But it shouldn't effect your understanding of the error. 

--------Error details--------
[ 66%] Building CXX object fmo/taxonomy-v1/CMakeFiles/fmo-taxonomy-v1.dir/algorithm-taxonomy.cpp.o
In file included from /Users/fmo_build/fmo-cpp-demo/fmo/taxonomy-v1/algorithm-taxonomy.cpp:1:
In file included from /Users/fmo_build/fmo-cpp-demo/fmo/taxonomy-v1/algorithm-taxonomy.hpp:4:
In file included from /Users/fmo_build/fmo-cpp-demo/fmo/../include/fmo/agglomerator.hpp:6:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/vector:270:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:644:
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:1880:58: error: destructor called on non-final 'fmo::TaxonomyV1::Component' that has virtual functions but
      non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    _LIBCPP_INLINE_VISIBILITY void destroy(pointer __p) {__p->_Tp();}
                                                         ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:1742:18: note: in instantiation of member function 'std::__1::allocator<fmo::TaxonomyV1::Component>::destroy'
      requested here
            {__a.destroy(__p);}
                 ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:1595:14: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<fmo::TaxonomyV1::Component> >::__destroy<fmo::TaxonomyV1::Component>' requested here
            {__destroy(__has_destroy<allocator_type, _Tp*>(), __a, __p);}
             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:421:25: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<fmo::TaxonomyV1::Component> >::destroy<fmo::TaxonomyV1::Component>' requested here
        __alloc_traits::destroy(__alloc(), _VSTD::__to_raw_pointer(--__soon_to_be_end));
                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:364:29: note: in instantiation of member function 'std::__1::__vector_base<fmo::TaxonomyV1::Component,
      std::__1::allocator<fmo::TaxonomyV1::Component> >::__destruct_at_end' requested here
    void clear() _NOEXCEPT {__destruct_at_end(__begin_);}
                            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:458:9: note: in instantiation of member function 'std::__1::__vector_base<fmo::TaxonomyV1::Component,
      std::__1::allocator<fmo::TaxonomyV1::Component> >::clear' requested here
        clear();
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1427:74: note: in instantiation of member function 'std::__1::__vector_base<fmo::TaxonomyV1::Component,
      std::__1::allocator<fmo::TaxonomyV1::Component> >::__vector_base' requested here
    template <class _Tp, class _Alloc> friend class _LIBCPP_TEMPLATE_VIS vector;
                                                                         ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:1880:64: note: qualify call to silence this warning
    _LIBCPP_INLINE_VISIBILITY void destroy(pointer __p) {__p->_Tp();}
                                                               ^
1 error generated.
make[2]: *** [fmo/taxonomy-v1/CMakeFiles/fmo-taxonomy-v1.dir/algorithm-taxonomy.cpp.o] Error 1
make[1]: *** [fmo/taxonomy-v1/CMakeFiles/fmo-taxonomy-v1.dir/all] Error 2
make: *** [all] Error 2

**Comment by rozumden** [comment]
Hi,

Thank you for your comment. The errors are due to some MacOS related C++ specifications. I've updated the code and it should run on MacOS now. Let me know if you have other issues.

**Comment by HANAND1979** [comment]
Hi, 

Thank you for your quick revert on this issue. While running 'make' on the updated code (on same MacOS), this error is coming.  

[ 89%] Building CXX object desktop/CMakeFiles/fmo-desktop.dir/loop-visualizer.cpp.o
/Users/fmo_build/fmo-cpp-demo/desktop/loop-visualizer.cpp:8:10: fatal error: 'boost/range/adaptor/reversed.hpp' file not found
#include <boost/range/adaptor/reversed.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [desktop/CMakeFiles/fmo-desktop.dir/loop-visualizer.cpp.o] Error 1
make[1]: *** [desktop/CMakeFiles/fmo-desktop.dir/all] Error 2
make: *** [all] Error 2

Note: I have boost installed - the installed version is boost: stable 1.72.0. Is it an issue with this?

**Comment by HANAND1979** [comment]
Hi,

The above issue got resolved. I added the below changes to CMakeLists.txt and the error got removed. [The reference can be found at https://stackoverflow.com/questions/24173330/cmake-is-not-able-to-find-boost-libraries]

SET (BOOST_ROOT "/usr/local/Cellar/boost/1.72.0_2")
SET (BOOST_INCLUDEDIR "/usr/local/Cellar/boost/1.72.0_2/include")
SET (BOOST_LIBRARYDIR "/usr/local/Cellar/boost/1.72.0_2/lib")

SET (BOOST_MIN_VERSION "1.72.0")
set (Boost_NO_BOOST_CMAKE ON)
FIND_PACKAGE(Boost ${BOOST_MIN_VERSION} REQUIRED)
if (NOT Boost_FOUND)
  message(FATAL_ERROR "Fatal error: Boost (version >= 1.72) required.")
else()
  message(STATUS "Setting up BOOST")
  message(STATUS " Includes - ${Boost_INCLUDE_DIRS}")
  message(STATUS " Library  - ${Boost_LIBRARY_DIRS}")
  include_directories(${Boost_INCLUDE_DIRS})
  link_directories(${Boost_LIBRARY_DIRS})
endif (NOT Boost_FOUND) 

Thank you once again. Your work is fantastic !
