### ISSUE TITLE
Output not getting written

### ISSUE THREAD

**Issue by HANAND1979** [rozumden/fmo-cpp-demo#3]
Hi Denys,

When i am running the program on one of the videos available on your website (in MacOS), the output file is not getting written. I have made the folder and specified the --record-dir flag too. What could i be missing? Here's the command being run.

$ fmo-desktop --input ping_pong_paint.mov --demo --dfactor 0.45 --record-dir output_fmo

**Comment by rozumden** [comment]
Hi Anand,

As mentioned in the readme, it's enough to press the "r" button to start recording. I've just tested it on MacOS and it was working. I hope it helps.

**Comment by HANAND1979** [comment]
Thank you, Denys. Sorry i think i missed noticing that in the readme. It's working. Thank you.
