### ISSUE TITLE
demo stuck

### ISSUE THREAD

**Issue by gitunit** [rozumden/fmo-cpp-demo#4]
not sure why but the demo is stuck at the following line
https://github.com/rozumden/fmo-cpp-demo/blob/32f532d174644183a63a40cbad29899907f946e5/fmo/algorithm.cpp#L84

am i missing a parameter? i've tried with camera and file, it never goes further this point in code.

edit: im on Ubuntu 18.04.

**Comment by rozumden** [comment]
Hi,

You must choose the type of visualization, e.g. --demo or --utiademo. One example would be "fmo-desktop --camera 0 --demo". What parameters did you use?

**Comment by gitunit** [comment]
sorry for the late reply, i was offline for some time. i chose every possible parameter (as in the README), everytime the application gets stuck at the same line shown above. im on ubuntu 18.04.
the pre-compiled demo for windows does work though with the same parameters/run configs.

**Comment by rozumden** [comment]
Can you please provide the exact command line which you used for running this demo?

**Comment by gitunit** [comment]
> Can you please provide the exact command line which you used for running this demo?

i tried all possibilities as mentioned in the README.

here is a list of some of those commands:

`/usr/local/bin/fmo-desktop --camera 0 --demo`
`/usr/local/bin/fmo-desktop --camera 0 --utiademo`
`/usr/local/bin/fmo-desktop --input ~/Downloads/17150385_rally1_out.mp4 --debug`
`/usr/local/bin/fmo-desktop --input ~/Downloads/17150385_rally1_out.mp4 --tutdemo`
`/usr/local/bin/fmo-desktop --input ~/Downloads/17150385_rally1_out.mp4 --demo`

and many many more.
for every command the program is stuck at the same place, it's never returning from aglorithm make.

**Comment by rozumden** [comment]
I've just tried downloading the git repository, compiling and running the commands you should above, and everything was working (also on Ubuntu 18.04). Which OpenCV version did you use? I recommend 3.4.0. Also, please try running from your build directory: "desktop/fmo-desktop --input ...". 

It's quite difficult to guess why the demo is stuck at that line, as it shouldn't be stuck there, it's essentially just a constructor. Do you see a GUI window at least?

**Comment by gitunit** [comment]
no gui window. i have to admit i'm using opencv 4.0. will try 3.4 and then report again if that worked. thx.

**Comment by gitunit** [comment]
i had success by going back to opencv 3 (im using conda and didnt want to compile opencv again, so i rather changed the code to work with 4.x but somehow it got stuck). for people using conda who don't want to compile, try: "conda install -c menpo opencv3".

i'm almost there, the command
`fmo-desktop --camera 0 --demo` works but not when i use a .mp4 video as input. then i get a `error: std::exception` while opening that file. any idea about that?

**Comment by rozumden** [comment]
Thanks for your feedback. 

I'm not sure. Maybe try some videos from our dataset, e.g. [ http://cmp.felk.cvut.cz/fmo/files/sequences/ping_pong_paint.mov ]. It works for this sequence for me.

**Comment by gitunit** [comment]
> I'm not sure. Maybe try some videos from our dataset, e.g. [ http://cmp.felk.cvut.cz/fmo/files/sequences/ping_pong_paint.mov ]. It works for this sequence for me.

same problem.

maybe the opencv3 version was not compiled with ffmpeg?

**Comment by rozumden** [comment]
That's possible. Make sure that OpenCV is compiled and compatible with ffmpeg.

**Comment by gitunit** [comment]
ok. i just checked the buildinformation of that opencv3 build and got following:

`  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      NO
      codec:                     NO
      format:                    NO
      util:                      NO
      swscale:                   NO
      resample:                  NO
      gentoo-style:              NO
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    UniCap:                      NO
    UniCap ucil:                 NO
    V4L/V4L2:                    NO/YES
    XIMEA:                       NO
    Xine:                        NO
    gPhoto2:                     NO
`

so, i guess i will have to compile myself to get a proper opencv3 version :) thx

**Comment by gitunit** [comment]
building opencv3 from scratch enabling ffmpeg and gtk finally did the trick.
